### ISSUE TITLE
Repository has no LICENSE

### ISSUE THREAD

**Issue by tatokis** [DJSures/NABU-LIB#1]
Thank you very much for your excellent work regarding the NABU computer.
I was looking into writing some software for it, and of course stumbled upon your repository. Unfortunately, while looking through the library, I noticed that there's no LICENSE/COPYING file, nor any licence headers that could indicate what this project is licensed under.

This mostly means that [people are not allowed to use your code for any purpose](https://choosealicense.com/no-permission/). Since the code was published, I assume the intent is to help other people write software using it, thus it would help clarify a lot of things if you added a licence to it.

In addition, I noticed the following comment in NABU-LIB:
https://github.com/DJSures/NABU-LIB/blob/33c94bcd16dde915dbdf057346a9680145d63151/NABULIB/NABU-LIB.c#L8-L9

The [TMS9918_Arduino](https://github.com/michalin/TMS9918_Arduino) project that the code was used from is licensed under the GNU GPL 3.

I am not a lawyer, however, it is my understanding that unless this project is now also licensed under the GPL, or that code is removed, then it is infringing on TMS9918_Arduino's copyright.

If NABU-LIB is licensed under the GPL, that means that all software using it might be considered derivative works, and thus will also need to be licensed under the GPL. Perhaps you can contact the author of TMS9918_Arduino and ask for some parts to be dual licensed under the GNU LGPL (Lesser General Public License) as well which is better suited for libraries, or some other licence instead.

Thank you for your time, and once again, thank you for your work!

**Comment by DJSures** [comment]
I added a license on the readme.md. There is no license :) Just use it. It's for a 40 year old computer. As for the arduino code that inspired some of the graphic functions - i've changed so much that it doesn't resemble it. You can give him credit, I did because his code helped me learn the TMS9918a. I highly doubt he'd have an issue with the few lines of similar code remaining :)
